image: archlinux
packages:
  - go-pie
  - annotatego-git
sources:
  - https://git.xenrox.net/~xenrox/srhtctl
environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
secrets:
  - 9b9e7b30-8dce-470c-9cad-0701fd958749 # ssh key
  - 7059f6bc-d2f4-42b5-9a69-421ac0bcecd4 # config.ini
triggers:
  - action: email
    condition: failure
    to: Thorben Günther <admin@xenrox.net>
tasks:
  - build: |
      cd srhtctl
      make
  - run: |
      cd srhtctl
      ./srhtctl completionZSH > /dev/null
  - annotate: |
      cd srhtctl
      annotatego -v git.xenrox.net/~xenrox/srhtctl... > annotations.json
      ./srhtctl git annotate --user xenrox --repo srhtctl annotations.json
  - github: |
      cd srhtctl
      git remote add github git@github.com:xenrox/srhtctl.git
      git push github master --follow-tags
