image: archlinux
packages:
  - go
sources:
  - https://git.xenrox.net/~xenrox/srhtctl
triggers:
  - action: email
    condition: failure
    to: Thorben Günther <admin@xenrox.net>
tasks:
  - build: |
      cd srhtctl
      go test -v ./...
